apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gen3-commons1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: helm/gen3
    repoURL: https://github.com/uc-cdis/gen3-helm
    targetRevision: master
    helm:
      releaseName: commons1
      valueFiles:
        - $values/commons1.org/values/values.yaml
        - $values/commons1.org/values/fence.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true